import type { LevelConfig } from './LevelData'

export const LEVEL_1: LevelConfig = {
  id: 'level1',
  name: 'Jungle Assault',
  totalDistance: 120,
  scrollSpeed: 4,
  background: {
    fogColor: '#aac8b6',
    fogNear: 14,
    fogFar: 48,
    skyColor: '#bcd7e4',
    groundColor: '#3f6b3c',
    parallaxLayers: [
      { color: '#4f7a5f', depth: 1, scrollFactor: 0.1 },
      { color: '#628e72', depth: 2, scrollFactor: 0.15 },
      { color: '#7aa287', depth: 3, scrollFactor: 0.2 },
    ],
  },
  terrain: [
    { x: 0, width: 30, height: 0.5, y: 0 },
    { x: 35, width: 10, height: 0.5, y: 0 },
    { x: 50, width: 8, height: 0.5, y: 0 },
    { x: 65, width: 20, height: 0.5, y: 0 },
    { x: 90, width: 30, height: 0.5, y: 0 },
  ],
  decorations: [
    { type: 'tree', x: 5, y: 0.5, scale: 1.2 },
    { type: 'tree', x: 8, y: 0.5 },
    { type: 'rock', x: 12, y: 0.5 },
    { type: 'tree', x: 18, y: 0.5, scale: 0.8 },
    { type: 'rock', x: 22, y: 0.5 },
    { type: 'tree', x: 28, y: 0.5, scale: 1.1 },
    { type: 'tree', x: 36, y: 0.5 },
    { type: 'tree', x: 39, y: 0.5, scale: 0.9 },
    { type: 'rock', x: 42, y: 0.5 },
    { type: 'tree', x: 52, y: 0.5, scale: 1.3 },
    { type: 'tree', x: 55, y: 0.5 },
    { type: 'rock', x: 58, y: 0.5 },
    { type: 'tree', x: 68, y: 0.5 },
    { type: 'tree', x: 72, y: 0.5, scale: 1.1 },
    { type: 'rock', x: 78, y: 0.5 },
    { type: 'tree', x: 82, y: 0.5 },
    { type: 'tree', x: 95, y: 0.5, scale: 1.2 },
    { type: 'tree', x: 100, y: 0.5 },
    { type: 'rock', x: 105, y: 0.5 },
    { type: 'tree', x: 110, y: 0.5 },
  ],
  waves: [
    { atDistance: 10, enemies: [{ type: 'soldier', count: 3, interval: 1.5 }] },
    { atDistance: 25, enemies: [{ type: 'soldier', count: 2, interval: 1 }, { type: 'runner', count: 2, interval: 2 }] },
    { atDistance: 40, enemies: [{ type: 'turret', count: 1, interval: 0 }] },
    { atDistance: 55, enemies: [{ type: 'soldier', count: 3, interval: 1 }, { type: 'flying', count: 2, interval: 2 }] },
    { atDistance: 75, enemies: [{ type: 'soldier', count: 4, interval: 1 }, { type: 'runner', count: 3, interval: 1.5 }] },
    { atDistance: 95, enemies: [{ type: 'soldier', count: 2, interval: 1 }, { type: 'turret', count: 2, interval: 0 }] },
  ],
  powerUpDrops: [
    { atDistance: 15, weapon: 'spread', position: [10, 4] },
    { atDistance: 45, weapon: 'rapid', position: [10, 5] },
    { atDistance: 80, weapon: 'laser', position: [10, 4] },
  ],
  boss: {
    type: 'tank',
    health: 30,
    phases: [
      { healthThreshold: 1.0, attackPattern: 'slow_aim', speed: 2 },
      { healthThreshold: 0.5, attackPattern: 'fast_spread', speed: 3 },
    ],
    scoreValue: 500,
  },
  music: 'level1',
}
